spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: false
      connection-timeout: 3000
    url: "jdbc:postgresql://127.0.0.1:5432/data_calculate_freight"
    #url: "jdbc:postgresql://172.17.0.2:5432/data_calculate_freight"
    username: postgres
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect