spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: false
      connection-timeout: 3000
    url: "jdbc:postgresql://localhost:5432/data_calculate_freight"
    username: postgres
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    baseline-on-migrate: true