INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 1, 'Acre', 'AC');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 2, 'Alagoas', 'AL');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 3, 'Amapá', 'AP');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 4, 'Amazonas', 'AM');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 5, 'Bahia', 'BA');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 6, 'Ceará', 'CE');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 7, 'Distrito Federal', 'DF');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 8, 'Espírito Santo', 'ES');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 9, 'Goiás', 'GO');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 10, 'Maranhão', 'MA');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 11, 'Mato Grosso', 'MT');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 12, 'Mato Grosso do Sul', 'MS');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 13, 'Minas Gerais', 'MG');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 14, 'Pará', 'PA');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 15, 'Paraíba', 'PB');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 16, 'Paraná', 'PR');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 17, 'Pernambuco', 'PE');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 18, 'Piauí', 'PI');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 19, 'Rio de Janeiro', 'RJ');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 20, 'Rio Grande do Norte', 'RN');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 21, 'Rio Grande do Sul', 'RS');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 22, 'Rondônia', 'RO');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 23, 'Roraima', 'RR');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 24, 'Santa Catarina', 'SC');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 25, 'São Paulo', 'SP');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 26, 'Sergipe', 'SE');
INSERT INTO public.country_states (date_create, id, state, state_code) VALUES(CURRENT_DATE, 27, 'Tocantins', 'TO');